#!/usr/bin/env bash
set -euxo pipefail

rm -rf dist
mkdir dist

docker build -t gnome-terminal-patch .

docker run --rm -ti \
    -v "$PWD:/src:ro" \
    -v "$PWD/dist:/dist:rw" \
    gnome-terminal-patch bash -euxc '\
    cd /tmp && \
    dget -ux http://archive.ubuntu.com/ubuntu/pool/main/g/gnome-terminal/gnome-terminal_3.28.2-1ubuntu1~18.04.1.dsc && \
    cd gnome-terminal*/ && \
    cp /src/re-enable-tab-tearing.patch debian/patches && \
    echo re-enable-tab-tearing.patch >> debian/patches/series && \
    cp /src/disable-copy-as-html.patch debian/patches && \
    echo disable-copy-as-html.patch >> debian/patches/series && \
    DEBFULLNAME="Anthony Sottile" DEBEMAIL=asottile@umich.edu \
        dch --local +asottile --distribution bionic "Re-enable tab tearing" && \
    DEBFULLNAME="Anthony Sottile" DEBEMAIL=asottile@umich.edu \
        dch --local +asottile --distribution bionic "Disable Copy as html" && \
    dpkg-buildpackage -us -uc -sa && \
    cp ../*.deb /dist/
'
